atoms/button作成
hiroto-cpu/takusyo-fronted-basic-last-assigment pull request #1
Opened 2023-03-03 06:42 UTC by hiroto-cpu

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか

2023-03-04 01:58 UTC, hiroto-cpu commented
https://63e61bf38edf3e5d78d3d99b-njvbyeevzu.chromatic.com/?path=/story/atoms-button--button

2023-03-04 02:40 UTC, renyagi reviewed
レスポンシブ対応できるようにしてください！
今回でいうと、storybookのsmall、medium、largeにおいて、それぞれでボタンのサイズが変わります。

2023-03-04 02:40 UTC, renyagi commented on src/components/atoms/button/button.html
> +<button class="button-tag">
タグを二重に作る必要はありません。
もっと簡単に記述することが出来ると思います！

2023-03-04 02:40 UTC, renyagi commented on src/components/atoms/button/button.scss
> +  background-color:#000000;
colorやfont-sizeなどはvariablesで定義されているのでそちらを用いてください。
例えば、color : #ffffff と記述する際には、color : $white と記述することができます。

2023-03-04 02:40 UTC, renyagi commented on src/components/atoms/button/button.html
> +  <h1>テキスト</h1>
class名は基本的につけたほうがいいと思います。

2023-03-04 02:40 UTC, renyagi commented on src/components/atoms/button/button.scss
> +.button-tag:hover{
$:hoverと書いても構いません

2023-03-04 02:40 UTC, renyagi commented on src/components/atoms/button/button.scss
> +  font-size:5px;
値が間違っています

2023-03-05 05:02 UTC, hiroto-cpu commented on src/components/atoms/button/button.scss
> +  background-color:#000000;
varaiblesとはなんですか？

2023-03-05 15:00 UTC, renyagi commented on src/components/atoms/button/button.scss
> +  background-color:#000000;
_variables.scssは今回の課題で用いられるpxや色に関して、変数を定義したファイルです。
ちなみにですが、@use "../../variables as *"というのはvariablesで定義された変数を*として扱うという意味であり、*は変数をimportしたファイルで用いる際に変数宣言前に何も書かなくて良いという意味を持ちます。
話が難しくなってしまいましたが、とりあえず_variables.scssは変数を定義したファイルであり、本課題では変数で書けるところは変数でかくということを意識してもらえれば大丈夫です。
説明が下手になってしまいましたが、分からなければまた聞いてください。

2023-03-11 09:41 UTC, ssshun3 commented
コードの行の隙間が少し気になるのでprettierが効いているか[こちら](https://zenn.dev/k_kazukiiiiii/articles/670ebae0005872)を参考にして確認してみてください。

コードに関して、メディアクエリが正しく書けていないためスタイルが適用されていません。また、今回の課題はデスクトップファーストであることも意識することができるといいですね。[こちら](https://www.wakuwakubank.com/posts/443-html-css-media-query/)を参考にして修正してみてください。

2023-03-11 09:42 UTC, ssshun3 commented on src/components/atoms/button/button.html
> +<button class="btn-con">テキスト</button>
Atoms/Buttonの作成の注意点にあるようにaタグで作成してください。
![image](https://user-images.githubusercontent.com/110015394/224476598-308800a2-4539-46df-a230-489536957182.png)

2023-03-11 09:42 UTC, ssshun3 commented on src/components/atoms/button/button.scss
> +@media screen and(min:600px){
色の変数指定($orange_bistreなど)はできているのでそれと同じ要領でブレイクポイントも数値ではなく変数で指定しいきましょう。また、メディアクエリを入れ子にすることもできます。
[参考](https://shinonome.io/frontend-basic/lastAssignment/storybook_sass/)
![image](https://user-images.githubusercontent.com/110015394/224477031-88561d41-be06-4c44-ae23-816b767ceae4.png)

2023-03-12 06:57 UTC, hiroto-cpu commented on src/components/atoms/button/button.scss
> +@media screen and(min:600px){
変数として定義されていない数字がある場合はどーすればいいんですか？

2023-03-22 13:21 UTC, SakaueYae reviewed
こちらhttps://github.com/hiroto-cpu/takusyo-fronted-basic-last-assigment/pull/1#discussion_r1133060429 でも指摘されていましたが、メディアクエリは入れ子にすることができます！コードの可読性が上がるため、このように記述することをおすすめします✨

2023-03-22 13:21 UTC, SakaueYae commented on src/components/atoms/button/button.html
> +<button class="btn-con">テキスト</button>
こちら修正をお願いします！
https://github.com/hiroto-cpu/takusyo-fronted-basic-last-assigment/pull/1#discussion_r1133059505

2023-03-22 13:21 UTC, SakaueYae commented on src/components/atoms/button/button.scss
> +  padding: 0px 16px;
お手本の値と異なるため確認お願いします！画面幅ごとに値が変化するため、メディアクエリ内に書いてみてください！

2023-03-22 13:21 UTC, SakaueYae commented on src/components/atoms/button/button.scss
> +@media screen and(min-width:$breakpoint-sm) {
課題ページにもあった通りデスクトップファーストにするため、max-widthで記述するようにしてみてください！今回の場合は画面幅がlg以上のスタイル、md以下のスタイル、s以下のスタイル、といったように書くと上手くいくと思います！前のレビュアーの方がコメントhttps://github.com/hiroto-cpu/takusyo-fronted-basic-last-assigment/pull/1#issuecomment-1464872667 に貼ってくださったページが参考になるかと思いますので、確認してみてください！

2023-03-22 13:21 UTC, SakaueYae commented on src/components/atoms/button/button.scss
> +  }
全体的にwidth、height、font-sizeがお手本と異なるため、figmaを見て修正お願いします！

2023-03-28 11:40 UTC, ssshun3 reviewed
見た目はかなりいいです！
scssだけでなくhtmlの修正もお願いします。

scssで一部コードが重複してたり、なくても見た目が変わらなそうなコードがあるのでそういったコードは[開発者ツール](https://playground.wraptas.site/67db90c0263c44d58b966b5f23f69917)を用いて確認し消せるようになれたらコードの量を減らせます！

またこの[サイト](https://playground.wraptas.site/d89ccb4cd1ec42f6b599e44e175e0d6f)を参考にしてコミットメッセージでは何を修正したか書けるようになりましょう！

2023-03-28 11:40 UTC, ssshun3 commented on src/components/atoms/button/button.html
> +<button class="btn-con">テキスト</button>
こちら修正をお願いします！
https://github.com/hiroto-cpu/takusyo-fronted-basic-last-assigment/pull/1#discussion_r1133059505

2023-03-28 11:40 UTC, ssshun3 commented on src/components/atoms/button/button.scss
> +  @media screen and(min-width:$breakpoint-lg) {
現在のコードでは`min-width`と`max-width`が混在しているため可読性が落ちてしまいます。
今回の課題はデスクトップファーストなので`max-width`のみを使用して実装してみましょう！

2023-03-28 11:40 UTC, ssshun3 commented on src/components/atoms/button/button.scss
> +.btn-con:hover {
&を用いて入れ子にしてみましょう！
[参考](https://shinonome.io/frontend-basic/lastAssignment/storybook_sass/)
![image](https://user-images.githubusercontent.com/110015394/228221084-1bb09264-6b00-4c7a-a813-413cd37482de.png)

2023-07-18 06:41 UTC, minezaki-mutsuki commented on src/components/atoms/button/button.html
> +  <p>コンセプト</p>
pタグ必要ないかと

2023-07-18 06:41 UTC, minezaki-mutsuki commented on src/components/atoms/button/button.scss
> +.btn-con:hover {
こちら対応お願いします！！

2023-07-18 06:41 UTC, minezaki-mutsuki commented on src/components/atoms/button/button.scss
> +  @media screen and(max-width:$breakpoint-lg) {
デフォルトのスタイルにwidthとheightが当たっていないため、画面幅が`breakpoint-lg`以上の時何も表示されていません。なのでデフォルトの幅として
```
width: 200px;
    height: 55px;
```
を当てましょう。

2023-07-18 06:41 UTC, minezaki-mutsuki commented on src/components/molecules/message/message.html
> +<!DOCTYPE html>
messageはこのプルリクに関係ないため削除しておいてください！

2023-07-18 06:41 UTC, minezaki-mutsuki commented on src/components/atoms/button/button.scss
> +  font-size: 14px;
フォントサイズや色は変数を使いましょう

2023-07-21 05:59 UTC, minezaki-mutsuki reviewed
message消えてないです！ファイル消しておきましょう！

2023-07-21 05:59 UTC, minezaki-mutsuki commented on src/components/atoms/button/button.scss
> +    height: 55px;
ここはデフォルトの指定と同じなので書かなくて大丈夫です。
@mediaとかhoverの記述はデフォルトから変更したい分のみcssを書くようにしましょう

2023-07-21 05:59 UTC, minezaki-mutsuki commented on src/components/atoms/button/button.scss
> +    height: 55px;
55pxはデフォルトにも書いてあるので書かなくても大丈夫です

2023-07-21 05:59 UTC, minezaki-mutsuki commented on src/components/atoms/button/button.scss
> +  display: inline-block;
このスタイル当たっていないので書かなくて大丈夫です。検証ツールでスタイリング確認できるので見てみるといいです！

2023-07-21 05:59 UTC, minezaki-mutsuki commented on src/components/atoms/button/button.scss
> +  border: 1px solid $gray_desertStorm;
boederいらないです。
これ消すと線が現れますが、これは多分bootstrapによるものだと思います。classをbtn-conにしているためだと思うので、classをbuttonなどにするといいと思います

2023-07-28 16:46 UTC, higashiji2000 requested changes

2023-07-28 16:46 UTC, higashiji2000 commented on src/components/atoms/button/button.scss
> +    weight: 180px;
```suggestion
    width: 180px;
```
weight -> width
お願いします！

2023-07-28 16:46 UTC, higashiji2000 commented on src/components/molecules/message/message.html
> +<!DOCTYPE html>
@hiroto-cpu 
ファイルを削除する方法はわかりますか？

2023-08-01 06:58 UTC, hiroto-cpu commented on src/components/molecules/message/message.html
> +<!DOCTYPE html>
あてずっぽうでやってみたんですがあってますか？

2023-08-02 10:07 UTC, higashiji2000 approved these changes
LGTMです👩🏿‍🌾

2023-08-16 10:55 UTC, merged